version: '3'

services:
  node:
    image: node:latest
    networks:
      - interne
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - 4000:4000
    command: "yarn start"
    environment:
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}

networks:
  interne:
    external:
      name: interne
